### ISSUE TITLE
当前版本下载下来，怎么加载不起来？

### ISSUE THREAD

**Issue by kaoshen** [angular-cn/ng-showcase#40]

**Comment by why520crazy** [comment]
报什么错误？bower install 安装前端类库了吗

**Comment by kaoshen** [comment]
类库都安装了。刚开始是这种错
angular.js:9563 Error: Failed to execute 'replaceState' on 'History': A history state object with URL 'file:///D:/workspace/ng-showcase/app/index.html#/' cannot be created in a document with origin 'null' and URL 'file:///D:/workspace/ng-showcase/app/index.html'.
到下面一堆就是  angular.js:78 Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached.

**Comment by why520crazy** [comment]
直接打开页面是不可以的，必须用grunt serve启动

**Comment by kaoshen** [comment]
擦  好的。谢了。

**Comment by why520crazy** [comment]
不客气
